RONDB-824: Remove termination sleep for data nodes (#21)
* Don't sleep on ndbmtd shutdown
* Added podAnnotations for data nodes
* Removed redundant template "rondb.checkDnsResolvable"
* Using 2 node groups in CI
* Bumping terminationGracePeriodSeconds again for Minikube
* CI: Log pods after every stability check
* Run data node activation in a loop
* *Also* activate node-id in initContainer
* Limit connect-retries with ndb_mgm

diff --git a/templates/ndbd.yaml b/templates/ndbd.yaml
--- a/templates/ndbd.yaml
+++ b/templates/ndbd.yaml
@@ -87,6 +87,11 @@ spec:
       labels:
         rondbService: {{ include "rondb.labels.rondbService.ndbmtd" $ }}
         nodeGroup: {{ $nodeGroup | quote }}
+      # This is an easy way to restart data nodes without changing specs.
+      annotations:
+{{- range $k, $v := $.Values.meta.ndbmtd.statefulSet.podAnnotations }}
+        {{ $k | quote }}: {{ $v | quote }}
+{{- end }}
     spec:
 {{- include "rondb.imagePullSecrets" $ | indent 6 }}
 {{- include "rondb.PodSecurityContext" $ | indent 6 }}
@@ -229,6 +234,12 @@ spec:
         env:
         - name: MGMD_HOST
           value: {{ include "rondb.mgmdHostname" $ }}
+        - name: NODE_GROUP
+          value: {{ $nodeGroup | quote }}
+        - name: POD_NAME
+          valueFrom:
+            fieldRef:
+              fieldPath: metadata.name
         command:
         - /bin/bash
         - -c
@@ -242,6 +253,22 @@ spec:
           # Placing this in initContainer because a main-container restart
           # will not change the Pod's IP address.
 {{ include "rondb.resolveOwnIp" $ | indent 10 }}
+
+          # Since the main container *deactivates* the nodes, it is important
+          # that the main container also activates the nodes. This is because StatefulSets
+          # will always try to restart a container (if it fails) and not the entire Pod.
+          # Hence, this is just placed here to accelerate the activation in main container
+          # so that the startupProbe is more accurate. The command is idempotent.
+          MGM_CONNECTSTRING=$MGMD_HOST:1186
+
+{{ include "rondb.nodeId" $ | indent 10 }}
+
+          echo "[K8s Entrypoint ndbmtd] Activating node id $NODE_ID via MGM client"
+          while ! ndb_mgm --ndb-connectstring="$MGM_CONNECTSTRING" --connect-retries=1 -e "$NODE_ID activate"; do
+            echo "[K8s Entrypoint ndbmtd] Activation failed. Retrying..." >&2
+            sleep $((NODE_GROUP + 2))
+          done
+          echo "[K8s Entrypoint ndbmtd] Activated node id $NODE_ID via MGM client"
       containers:
       - name: ndbmtd
         image: {{ include "image_address" (dict "image" $.Values.images.rondb) }}
